### ISSUE TITLE
Several quizzes seem to be missing from 2A-L1

### ISSUE THREAD

**Issue by N3rdyM1k3** [ApoorvaBeedu/CV-lecture-quizzes-python#3]
Some of the topics don't seem to be covered by the video/demo:

Generating Gaussian Noise
Crop an image
Effect of Sigma on Gaussian Noise 
Multiple a scalar

Some of these are probably obvious but it's hard to tell what we need to know this early in the semester.

**Comment by N3rdyM1k3** [comment]
Watching through, some of these are standard quizzes and not matlab quizes, but I don't think all of them are.

**Comment by mloo3** [comment]
I checked the four that you mentioned and the rest of the lecture slides in case there were any others that were missing. 

The topics that these quizzes/lectures cover are important, but we felt that the coding part of the quizzes were not substantial enough to convert into python. 
Eg. "Crop an Image" asks for you to find out the size of a cropped image, and Generate Gaussian Noise requires you to play around with generating Gaussian values.
